CREATE TABLE "prop_firms" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(80) NOT NULL,
	"name" varchar(120) NOT NULL,
	"logo_url" text,
	"challenge_fee_usd" integer,
	"account_size_usd" integer,
	"max_daily_drawdown_pct" integer,
	"max_total_drawdown_pct" integer,
	"profit_target_pct" integer,
	"min_trading_days" integer,
	"allows_overnight" boolean DEFAULT true NOT NULL,
	"allows_news_trading" boolean DEFAULT true NOT NULL,
	"allows_ea_bots" boolean DEFAULT true NOT NULL,
	"payout_split_pct" integer,
	"first_payout_days" integer,
	"trust_score" integer DEFAULT 70 NOT NULL,
	"country" varchar(80),
	"regulation_note" text,
	"affiliate_url" text,
	"affiliate_label" varchar(120),
	"is_sponsored" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "prop_firms_slug_unique" UNIQUE("slug")
);
